### ISSUE TITLE
Consider using nginx in alpine

### ISSUE THREAD

**Issue by alekssaul** [azwickey-pivotal/pks-walkthrough#1]
As Fortune-UI Dockerfile tag: `https://github.com/azwickey-pivotal/pks-walkthrough/blob/master/apps/fortune-ui/Dockerfile#L1`

85% leaner (7 MB vs 44 MB)

https://hub.docker.com/r/library/nginx/tags/ 

Can shoot a PR when I get time to test, shouldn't be a breaking change tho.

**Comment by azwickey-pivotal** [comment]
Good call.  That will speed things up.

**Comment by azwickey-pivotal** [comment]
Updated all the linux images to be based on alpine.  Much smaller now.
